# Generated by Django 5.0.6 on 2026-07-03 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('english', 'Ingliz tili'), ('russian', 'Rus tili'), ('german', 'Nemis tili'), ('turkish', 'Turk tili'), ('math', 'Matematika')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_language', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, help_text='Frontend uchun ikonka nomi', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('order', models.PositiveSmallIntegerField(help_text='Daraja tartibi, kichikdan kattaga')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='subjects.subject')),
            ],
            options={
                'ordering': ['subject', 'order'],
                'unique_together': {('subject', 'code')},
            },
        ),
    ]
